=== tvorexspecialist/m2automation/setup/src/Magento/Setup/Model/Declaration/Schema/config/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
* Copyright Â© Magento, Inc. All rights reserved.
* See COPYING.txt for license details.
*/
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!--Types-->
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/decimals/decimal.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/decimals/float.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/decimals/double.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/integers/integer.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/integers/biginteger.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/integers/smallinteger.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/integers/tinyinteger.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/texts/text.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/texts/longtext.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/texts/mediumtext.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/texts/varchar.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/binaries/blob.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/binaries/mediumblob.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/binaries/longblob.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/binaries/varbinary.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/datetime/timestamp.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/datetime/datetime.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/datetime/date.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/boolean.xsd" />
    <!--Constraints-->
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/constraints/foreign.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/constraints/unique.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/constraints/primary.xsd" />
    <!--Indexes-->
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/index.xsd" />

    <xs:element name="schema">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="table" type="table"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="table">
        <xs:annotation>
            <xs:documentation>
                Table definition. Here we can found column, constraints and indexes
            </xs:documentation>
        </xs:annotation>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="column" />
            <xs:element name="constraint" />
            <xs:element name="index" type="index" />
        </xs:choice>
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="resource" type="resourceType" />
    </xs:complexType>

    <xs:simpleType name="resourceType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="default" />
            <xs:enumeration value="checkout" />
            <xs:enumeration value="sales" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== tvorexspecialist/m2automation/app/code/Magento/Integration/etc/db_schema.xml
<?xml version="1.0"?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:setup:Model/Declaration/Schema/etc/schema.xsd">
  <table name="oauth_consumer" resource="default" engine="innodb">
    <column xsi:type="int" name="entity_id" padding="10" unsigned="true" nullable="false" identity="true"/>
    <column xsi:type="timestamp" name="created_at" on_update="false" nullable="false" default="CURRENT_TIMESTAMP"/>
    <column xsi:type="timestamp" name="updated_at" on_update="true" nullable="true" default="0"/>
    <column xsi:type="varchar" name="name" nullable="false" length="255"/>
    <column xsi:type="varchar" name="key" nullable="false" length="32"/>
    <column xsi:type="varchar" name="secret" nullable="false" length="32"/>
    <column xsi:type="text" name="callback_url" nullable="true"/>
    <column xsi:type="text" name="rejected_callback_url" nullable="false"/>
    <constraint xsi:type="primary" name="PRIMARY">
      <column name="entity_id"/>
    </constraint>
    <constraint xsi:type="unique" name="OAUTH_CONSUMER_KEY">
      <column name="key"/>
    </constraint>
    <constraint xsi:type="unique" name="OAUTH_CONSUMER_SECRET">
      <column name="secret"/>
    </constraint>
    <index name="OAUTH_CONSUMER_CREATED_AT" indexType="btree">
      <column name="created_at"/>
    </index>
    <index name="OAUTH_CONSUMER_UPDATED_AT" indexType="btree">
      <column name="updated_at"/>
    </index>
  </table>
  <table name="oauth_token" resource="default" engine="innodb">
    <column xsi:type="int" name="entity_id" padding="10" unsigned="true" nullable="false" identity="true"/>
    <column xsi:type="int" name="consumer_id" padding="10" unsigned="true" nullable="true" identity="false"/>
    <column xsi:type="int" name="admin_id" padding="10" unsigned="true" nullable="true" identity="false"/>
    <column xsi:type="int" name="customer_id" padding="10" unsigned="true" nullable="true" identity="false"/>
    <column xsi:type="varchar" name="type" nullable="false" length="16"/>
    <column xsi:type="varchar" name="token" nullable="false" length="32"/>
    <column xsi:type="varchar" name="secret" nullable="false" length="32"/>
    <column xsi:type="varchar" name="verifier" nullable="true" length="32"/>
    <column xsi:type="text" name="callback_url" nullable="false"/>
    <column xsi:type="smallint" name="revoked" padding="5" unsigned="true" nullable="false" identity="false" default="0"/>
    <column xsi:type="smallint" name="authorized" padding="5" unsigned="true" nullable="false" identity="false" default="0"/>
    <column xsi:type="int" name="user_type" padding="11" unsigned="false" nullable="true" identity="false"/>
    <column xsi:type="timestamp" name="created_at" on_update="false" nullable="false" default="CURRENT_TIMESTAMP"/>
    <constraint xsi:type="primary" name="PRIMARY">
      <column name="entity_id"/>
    </constraint>
    <constraint xsi:type="foreign" name="OAUTH_TOKEN_ADMIN_ID_ADMIN_USER_USER_ID" table="oauth_token" column="admin_id" referenceTable="admin_user" referenceColumn="user_id" onDelete="CASCADE"/>
    <constraint xsi:type="foreign" name="OAUTH_TOKEN_CONSUMER_ID_OAUTH_CONSUMER_ENTITY_ID" table="oauth_token" column="consumer_id" referenceTable="oauth_consumer" referenceColumn="entity_id" onDelete="CASCADE"/>
    <constraint xsi:type="foreign" name="OAUTH_TOKEN_CUSTOMER_ID_CUSTOMER_ENTITY_ENTITY_ID" table="oauth_token" column="customer_id" referenceTable="customer_entity" referenceColumn="entity_id" onDelete="CASCADE"/>
    <constraint xsi:type="unique" name="OAUTH_TOKEN_TOKEN">
      <column name="token"/>
    </constraint>
    <index name="OAUTH_TOKEN_CONSUMER_ID" indexType="btree">
      <column name="consumer_id"/>
    </index>
  </table>
  <table name="oauth_nonce" resource="default" engine="innodb">
    <column xsi:type="varchar" name="nonce" nullable="false" length="32"/>
    <column xsi:type="int" name="timestamp" padding="10" unsigned="true" nullable="false" identity="false"/>
    <column xsi:type="int" name="consumer_id" padding="10" unsigned="true" nullable="false" identity="false"/>
    <constraint xsi:type="foreign" name="OAUTH_NONCE_CONSUMER_ID_OAUTH_CONSUMER_ENTITY_ID" table="oauth_nonce" column="consumer_id" referenceTable="oauth_consumer" referenceColumn="entity_id" onDelete="CASCADE"/>
    <constraint xsi:type="unique" name="OAUTH_NONCE_NONCE_CONSUMER_ID">
      <column name="nonce"/>
      <column name="consumer_id"/>
    </constraint>
  </table>
  <table name="integration" resource="default" engine="innodb">
    <column xsi:type="int" name="integration_id" padding="10" unsigned="true" nullable="false" identity="true"/>
    <column xsi:type="varchar" name="name" nullable="false" length="255"/>
    <column xsi:type="varchar" name="email" nullable="false" length="255"/>
    <column xsi:type="varchar" name="endpoint" nullable="true" length="255"/>
    <column xsi:type="smallint" name="status" padding="5" unsigned="true" nullable="false" identity="false"/>
    <column xsi:type="int" name="consumer_id" padding="10" unsigned="true" nullable="true" identity="false"/>
    <column xsi:type="timestamp" name="created_at" on_update="false" nullable="false" default="CURRENT_TIMESTAMP"/>
    <column xsi:type="timestamp" name="updated_at" on_update="true" nullable="false" default="0"/>
    <column xsi:type="smallint" name="setup_type" padding="5" unsigned="true" nullable="false" identity="false" default="0"/>
    <column xsi:type="varchar" name="identity_link_url" nullable="true" length="255"/>
    <constraint xsi:type="primary" name="PRIMARY">
      <column name="integration_id"/>
    </constraint>
    <constraint xsi:type="foreign" name="INTEGRATION_CONSUMER_ID_OAUTH_CONSUMER_ENTITY_ID" table="integration" column="consumer_id" referenceTable="oauth_consumer" referenceColumn="entity_id" onDelete="CASCADE"/>
    <constraint xsi:type="unique" name="INTEGRATION_NAME">
      <column name="name"/>
    </constraint>
    <constraint xsi:type="unique" name="INTEGRATION_CONSUMER_ID">
      <column name="consumer_id"/>
    </constraint>
  </table>
  <table name="oauth_token_request_log" resource="default" engine="innodb">
    <column xsi:type="int" name="log_id" padding="10" unsigned="true" nullable="false" identity="true"/>
    <column xsi:type="varchar" name="user_name" nullable="false" length="255"/>
    <column xsi:type="smallint" name="user_type" padding="5" unsigned="true" nullable="false" identity="false"/>
    <column xsi:type="smallint" name="failures_count" padding="5" unsigned="true" nullable="true" identity="false" default="0"/>
    <column xsi:type="timestamp" name="lock_expires_at" on_update="true" nullable="true" default="CURRENT_TIMESTAMP"/>
    <constraint xsi:type="primary" name="PRIMARY">
      <column name="log_id"/>
    </constraint>
    <constraint xsi:type="unique" name="OAUTH_TOKEN_REQUEST_LOG_USER_NAME_USER_TYPE">
      <column name="user_name"/>
      <column name="user_type"/>
    </constraint>
  </table>
</schema>

=== tvorexspecialist/m2automation/app/code/Magento/SendFriend/etc/db_schema.xml
<?xml version="1.0"?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:setup:Model/Declaration/Schema/etc/schema.xsd">
  <table name="sendfriend_log" resource="default">
    <column xsi:type="int" name="log_id" padding="10" unsigned="true" nullable="false" identity="true"/>
    <column xsi:type="bigint" name="ip" padding="20" unsigned="true" nullable="false" identity="false" default="0"/>
    <column xsi:type="int" name="time" padding="10" unsigned="true" nullable="false" identity="false" default="0"/>
    <column xsi:type="smallint" name="website_id" padding="5" unsigned="true" nullable="false" identity="false" default="0"/>
    <constraint xsi:type="primary" name="PRIMARY">
      <column name="log_id"/>
    </constraint>
    <index name="SENDFRIEND_LOG_IP" indexType="btree">
      <column name="ip"/>
    </index>
    <index name="SENDFRIEND_LOG_TIME" indexType="btree">
      <column name="time"/>
    </index>
  </table>
</schema>

=== tvorexspecialist/m2automation/app/code/Magento/Swatches/etc/db_schema.xml
<?xml version="1.0"?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:setup:Model/Declaration/Schema/etc/schema.xsd">
    <table name="catalog_eav_attribute" resource="default">
        <column xsi:type="text" name="additional_data" nullable="true"/>
    </table>
    <table name="eav_attribute_option_swatch" resource="default">
        <column xsi:type="int" name="swatch_id" padding="11" unsigned="true" nullable="false" identity="true"/>
        <column xsi:type="int" name="option_id" padding="11" unsigned="true" nullable="false" identity="false"/>
        <column xsi:type="smallint" name="store_id" padding="6" unsigned="true" nullable="false" identity="false"/>
        <column xsi:type="smallint" name="type" padding="6" unsigned="true" nullable="false" identity="false"/>
        <column xsi:type="varchar" name="value" nullable="true" length="255"/>
        <constraint xsi:type="primary" name="PRIMARY">
            <column name="swatch_id"/>
        </constraint>
        <constraint xsi:type="foreign" name="EAV_ATTRIBUTE_OPTION_SWATCH_STORE_ID_STORE_STORE_ID"
                    table="eav_attribute_option_swatch" column="store_id" referenceTable="store"
                    referenceColumn="store_id" onDelete="CASCADE"/>
        <constraint xsi:type="foreign" name="EAV_ATTR_OPT_SWATCH_OPT_ID_EAV_ATTR_OPT_OPT_ID"
                    table="eav_attribute_option_swatch" column="option_id" referenceTable="eav_attribute_option"
                    referenceColumn="option_id" onDelete="CASCADE"/>
        <constraint xsi:type="unique" name="EAV_ATTRIBUTE_OPTION_SWATCH_STORE_ID_OPTION_ID">
            <column name="store_id"/>
            <column name="option_id"/>
        </constraint>
        <index name="EAV_ATTRIBUTE_OPTION_SWATCH_SWATCH_ID" indexType="btree">
            <column name="swatch_id"/>
        </index>
    </table>
</schema>
