=== tvorexspecialist/m2automation/setup/src/Magento/Setup/Model/Declaration/Schema/config/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
* Copyright Â© Magento, Inc. All rights reserved.
* See COPYING.txt for license details.
*/
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!--Types-->
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/decimals/decimal.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/decimals/float.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/decimals/double.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/integers/integer.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/integers/biginteger.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/integers/smallinteger.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/integers/tinyinteger.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/texts/text.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/texts/longtext.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/texts/mediumtext.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/texts/varchar.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/binaries/blob.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/binaries/mediumblob.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/binaries/longblob.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/binaries/varbinary.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/datetime/timestamp.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/datetime/datetime.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/datetime/date.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/types/boolean.xsd" />
    <!--Constraints-->
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/constraints/foreign.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/constraints/unique.xsd" />
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/constraints/primary.xsd" />
    <!--Indexes-->
    <xs:include schemaLocation="urn:magento:setup:Model/Declaration/Schema/config/index.xsd" />

    <xs:element name="schema">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="table" type="table"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="table">
        <xs:annotation>
            <xs:documentation>
                Table definition. Here we can found column, constraints and indexes
            </xs:documentation>
        </xs:annotation>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element name="column" />
            <xs:element name="constraint" />
            <xs:element name="index" type="index" />
        </xs:choice>
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="resource" type="resourceType" />
    </xs:complexType>

    <xs:simpleType name="resourceType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="default" />
            <xs:enumeration value="checkout" />
            <xs:enumeration value="sales" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== tvorexspecialist/m2automation/app/code/Magento/Store/etc/db_schema.xml
<?xml version="1.0"?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:setup:Model/Declaration/Schema/etc/schema.xsd">
    <table name="store_website" resource="default">
        <column xsi:type="smallint" name="website_id" padding="6" unsigned="true" nullable="false" identity="true"/>
        <column xsi:type="varchar" name="code" nullable="true" length="32"/>
        <column xsi:type="varchar" name="name" nullable="true" length="64"/>
        <column xsi:type="smallint" name="sort_order" padding="6" unsigned="true" nullable="false" identity="false"
                default="0"/>
        <column xsi:type="smallint" name="default_group_id" padding="6" unsigned="true" nullable="false"
                identity="false" default="0"/>
        <column xsi:type="smallint" name="is_default" padding="6" unsigned="true" nullable="true" identity="false"
                default="0"/>
        <constraint xsi:type="primary" name="PRIMARY">
            <column name="website_id"/>
        </constraint>
        <constraint xsi:type="unique" name="STORE_WEBSITE_CODE">
            <column name="code"/>
        </constraint>
        <index name="STORE_WEBSITE_SORT_ORDER" indexType="btree">
            <column name="sort_order"/>
        </index>
        <index name="STORE_WEBSITE_DEFAULT_GROUP_ID" indexType="btree">
            <column name="default_group_id"/>
        </index>
    </table>
    <table name="store_group" resource="default">
        <column xsi:type="smallint" name="group_id" padding="6" unsigned="true" nullable="false" identity="true"/>
        <column xsi:type="smallint" name="website_id" padding="6" unsigned="true" nullable="false" identity="false"
                default="0"/>
        <column xsi:type="varchar" name="name" nullable="false" length="255"/>
        <column xsi:type="int" name="root_category_id" padding="11" unsigned="true" nullable="false" identity="false"
                default="0"/>
        <column xsi:type="smallint" name="default_store_id" padding="6" unsigned="true" nullable="false"
                identity="false" default="0"/>
        <column xsi:type="varchar" name="code" nullable="true" length="32"/>
        <constraint xsi:type="primary" name="PRIMARY">
            <column name="group_id"/>
        </constraint>
        <constraint xsi:type="foreign" name="STORE_GROUP_WEBSITE_ID_STORE_WEBSITE_WEBSITE_ID" table="store_group"
                    column="website_id" referenceTable="store_website" referenceColumn="website_id" onDelete="CASCADE"/>
        <constraint xsi:type="unique" name="STORE_GROUP_CODE">
            <column name="code"/>
        </constraint>
        <index name="STORE_GROUP_WEBSITE_ID" indexType="btree">
            <column name="website_id"/>
        </index>
        <index name="STORE_GROUP_DEFAULT_STORE_ID" indexType="btree">
            <column name="default_store_id"/>
        </index>
    </table>
    <table name="store" resource="default">
        <column xsi:type="smallint" name="store_id" padding="6" unsigned="true" nullable="false" identity="true"/>
        <column xsi:type="varchar" name="code" nullable="true" length="32"/>
        <column xsi:type="smallint" name="website_id" padding="6" unsigned="true" nullable="false" identity="false"
                default="0"/>
        <column xsi:type="smallint" name="group_id" padding="6" unsigned="true" nullable="false" identity="false"
                default="0"/>
        <column xsi:type="varchar" name="name" nullable="false" length="255"/>
        <column xsi:type="smallint" name="sort_order" padding="6" unsigned="true" nullable="false" identity="false"
                default="0"/>
        <column xsi:type="smallint" name="is_active" padding="6" unsigned="true" nullable="false" identity="false"
                default="0"/>
        <constraint xsi:type="primary" name="PRIMARY">
            <column name="store_id"/>
        </constraint>
        <constraint xsi:type="foreign" name="STORE_GROUP_ID_STORE_GROUP_GROUP_ID" table="store" column="group_id"
                    referenceTable="store_group" referenceColumn="group_id" onDelete="CASCADE"/>
        <constraint xsi:type="foreign" name="STORE_WEBSITE_ID_STORE_WEBSITE_WEBSITE_ID" table="store"
                    column="website_id" referenceTable="store_website" referenceColumn="website_id" onDelete="CASCADE"/>
        <constraint xsi:type="unique" name="STORE_CODE">
            <column name="code"/>
        </constraint>
        <index name="STORE_WEBSITE_ID" indexType="btree">
            <column name="website_id"/>
        </index>
        <index name="STORE_IS_ACTIVE_SORT_ORDER" indexType="btree">
            <column name="is_active"/>
            <column name="sort_order"/>
        </index>
        <index name="STORE_GROUP_ID" indexType="btree">
            <column name="group_id"/>
        </index>
    </table>
</schema>

=== tvorexspecialist/m2automation/app/code/Magento/UrlRewrite/etc/db_schema.xml
<?xml version="1.0"?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:setup:Model/Declaration/Schema/etc/schema.xsd">
    <table name="url_rewrite" resource="default">
        <column xsi:type="int" name="url_rewrite_id" padding="11" unsigned="true" nullable="false" identity="true"/>
        <column xsi:type="varchar" name="entity_type" nullable="false" length="32"/>
        <column xsi:type="int" name="entity_id" padding="11" unsigned="true" nullable="false" identity="false"/>
        <column xsi:type="varchar" name="request_path" nullable="true" length="255"/>
        <column xsi:type="varchar" name="target_path" nullable="true" length="255"/>
        <column xsi:type="smallint" name="redirect_type" padding="6" unsigned="true" nullable="false" identity="false"
                default="0"/>
        <column xsi:type="smallint" name="store_id" padding="6" unsigned="true" nullable="false" identity="false"/>
        <column xsi:type="varchar" name="description" nullable="true" length="255"/>
        <column xsi:type="smallint" name="is_autogenerated" padding="6" unsigned="true" nullable="false"
                identity="false" default="0"/>
        <column xsi:type="varchar" name="metadata" nullable="true" length="255"/>
        <constraint xsi:type="primary" name="PRIMARY">
            <column name="url_rewrite_id"/>
        </constraint>
        <constraint xsi:type="unique" name="URL_REWRITE_REQUEST_PATH_STORE_ID">
            <column name="request_path"/>
            <column name="store_id"/>
        </constraint>
        <index name="URL_REWRITE_TARGET_PATH" indexType="btree">
            <column name="target_path"/>
        </index>
        <index name="URL_REWRITE_STORE_ID_ENTITY_ID" indexType="btree">
            <column name="store_id"/>
            <column name="entity_id"/>
        </index>
    </table>
</schema>

=== tvorexspecialist/m2automation/app/code/Magento/CatalogUrlRewrite/etc/db_schema.xml
<?xml version="1.0"?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:setup:Model/Declaration/Schema/etc/schema.xsd">
  <table name="catalog_url_rewrite_product_category" resource="default">
    <column xsi:type="int" name="url_rewrite_id" padding="10" unsigned="true" nullable="false" identity="false"/>
    <column xsi:type="int" name="category_id" padding="10" unsigned="true" nullable="false" identity="false"/>
    <column xsi:type="int" name="product_id" padding="10" unsigned="true" nullable="false" identity="false"/>
    <constraint xsi:type="foreign" name="CAT_URL_REWRITE_PRD_CTGR_PRD_ID_CAT_PRD_ENTT_ENTT_ID" table="catalog_url_rewrite_product_category" column="product_id" referenceTable="catalog_product_entity" referenceColumn="entity_id" onDelete="CASCADE"/>
    <constraint xsi:type="foreign" name="FK_BB79E64705D7F17FE181F23144528FC8" table="catalog_url_rewrite_product_category" column="url_rewrite_id" referenceTable="url_rewrite" referenceColumn="url_rewrite_id" onDelete="CASCADE"/>
    <index name="CATALOG_URL_REWRITE_PRODUCT_CATEGORY_CATEGORY_ID_PRODUCT_ID" indexType="btree">
      <column name="category_id"/>
      <column name="product_id"/>
    </index>
  </table>
</schema>

=== tvorexspecialist/m2automation/app/code/Magento/Security/etc/db_schema.xml
<?xml version="1.0"?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:setup:Model/Declaration/Schema/etc/schema.xsd">
    <table name="admin_user_session" resource="default">
        <column xsi:type="int" name="id" padding="11" unsigned="true" nullable="false" identity="true"/>
        <column xsi:type="varchar" name="session_id" nullable="false" length="128"/>
        <column xsi:type="int" name="user_id" padding="11" unsigned="true" nullable="true" identity="false"/>
        <column xsi:type="smallint" name="status" padding="6" unsigned="true" nullable="false" identity="false"
                default="1"/>
        <column xsi:type="timestamp" name="created_at" on_update="false" nullable="false" default="CURRENT_TIMESTAMP"/>
        <column xsi:type="timestamp" name="updated_at" on_update="true" nullable="false" default="CURRENT_TIMESTAMP"/>
        <column xsi:type="varchar" name="ip" nullable="false" length="15" disabled="1"/>
        <constraint xsi:type="primary" name="PRIMARY">
            <column name="id"/>
        </constraint>
        <constraint xsi:type="foreign" name="ADMIN_USER_SESSION_USER_ID_ADMIN_USER_USER_ID" table="admin_user_session"
                    column="user_id" referenceTable="admin_user" referenceColumn="user_id" onDelete="CASCADE"/>
        <index name="ADMIN_USER_SESSION_SESSION_ID" indexType="btree">
            <column name="session_id"/>
        </index>
        <index name="ADMIN_USER_SESSION_USER_ID" indexType="btree">
            <column name="user_id"/>
        </index>
    </table>
    <table name="password_reset_request_event" resource="default">
        <column xsi:type="int" name="id" padding="11" unsigned="true" nullable="false" identity="true"/>
        <column xsi:type="smallint" name="request_type" padding="6" unsigned="true" nullable="false" identity="false"/>
        <column xsi:type="varchar" name="account_reference" nullable="true" length="255"/>
        <column xsi:type="timestamp" name="created_at" on_update="false" nullable="false" default="CURRENT_TIMESTAMP"/>
        <column xsi:type="varchar" name="ip" nullable="false" length="15" disabled="1"/>
        <constraint xsi:type="primary" name="PRIMARY">
            <column name="id"/>
        </constraint>
        <index name="PASSWORD_RESET_REQUEST_EVENT_ACCOUNT_REFERENCE" indexType="btree">
            <column name="account_reference"/>
        </index>
        <index name="PASSWORD_RESET_REQUEST_EVENT_CREATED_AT" indexType="btree">
            <column name="created_at"/>
        </index>
    </table>
</schema>

=== tvorexspecialist/m2automation/dev/tests/setup-integration/_files/Magento/TestSetupDeclarationModule4/etc/db_schema.xml
<?xml version="1.0"?>
<!--
/**
 * Copyright Â© Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:setup:Model/Declaration/Schema/etc/schema.xsd">
    <table name="test_table" resource="default" comment="Test Table">
        <column xsi:type="int" name="page_id"  />
        <column xsi:type="varchar" name="email" />
        <column xsi:type="varchar" name="title" />
        <constraint xsi:type="primary" name="PRIMARY">
            <column name="page_id" />
            <column name="email" />
        </constraint>
    </table>
</schema>

=== tvorexspecialist/m2automation/app/code/Magento/CatalogInventory/etc/db_schema.xml
<?xml version="1.0"?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:setup:Model/Declaration/Schema/etc/schema.xsd">
  <table name="cataloginventory_stock" resource="default" engine="innodb">
    <column xsi:type="smallint" name="stock_id" padding="5" unsigned="true" nullable="false" identity="true"/>
    <column xsi:type="smallint" name="website_id" padding="5" unsigned="true" nullable="false" identity="false"/>
    <column xsi:type="varchar" name="stock_name" nullable="true" length="255"/>
    <constraint xsi:type="primary" name="PRIMARY">
      <column name="stock_id"/>
    </constraint>
    <index name="CATALOGINVENTORY_STOCK_WEBSITE_ID" indexType="btree">
      <column name="website_id"/>
    </index>
  </table>
  <table name="cataloginventory_stock_item" resource="default" engine="innodb">
    <column xsi:type="int" name="item_id" padding="10" unsigned="true" nullable="false" identity="true"/>
    <column xsi:type="int" name="product_id" padding="10" unsigned="true" nullable="false" identity="false" default="0"/>
    <column xsi:type="smallint" name="stock_id" padding="5" unsigned="true" nullable="false" identity="false" default="0"/>
    <column xsi:type="decimal" name="qty" scale="4" precission="12" unsigned="false" nullable="true"/>
    <column xsi:type="decimal" name="min_qty" scale="4" precission="12" unsigned="false" nullable="false" default="0"/>
    <column xsi:type="smallint" name="use_config_min_qty" padding="5" unsigned="true" nullable="false" identity="false" default="1"/>
    <column xsi:type="smallint" name="is_qty_decimal" padding="5" unsigned="true" nullable="false" identity="false" default="0"/>
    <column xsi:type="smallint" name="backorders" padding="5" unsigned="true" nullable="false" identity="false" default="0"/>
    <column xsi:type="smallint" name="use_config_backorders" padding="5" unsigned="true" nullable="false" identity="false" default="1"/>
    <column xsi:type="decimal" name="min_sale_qty" scale="4" precission="12" unsigned="false" nullable="false" default="1"/>
    <column xsi:type="smallint" name="use_config_min_sale_qty" padding="5" unsigned="true" nullable="false" identity="false" default="1"/>
    <column xsi:type="decimal" name="max_sale_qty" scale="4" precission="12" unsigned="false" nullable="false" default="0"/>
    <column xsi:type="smallint" name="use_config_max_sale_qty" padding="5" unsigned="true" nullable="false" identity="false" default="1"/>
    <column xsi:type="smallint" name="is_in_stock" padding="5" unsigned="true" nullable="false" identity="false" default="0"/>
    <column xsi:type="timestamp" name="low_stock_date" on_update="false" nullable="true"/>
    <column xsi:type="decimal" name="notify_stock_qty" scale="4" precission="12" unsigned="false" nullable="true"/>
    <column xsi:type="smallint" name="use_config_notify_stock_qty" padding="5" unsigned="true" nullable="false" identity="false" default="1"/>
    <column xsi:type="smallint" name="manage_stock" padding="5" unsigned="true" nullable="false" identity="false" default="0"/>
    <column xsi:type="smallint" name="use_config_manage_stock" padding="5" unsigned="true" nullable="false" identity="false" default="1"/>
    <column xsi:type="smallint" name="stock_status_changed_auto" padding="5" unsigned="true" nullable="false" identity="false" default="0"/>
    <column xsi:type="smallint" name="use_config_qty_increments" padding="5" unsigned="true" nullable="false" identity="false" default="1"/>
    <column xsi:type="decimal" name="qty_increments" scale="4" precission="12" unsigned="false" nullable="false" default="0"/>
    <column xsi:type="smallint" name="use_config_enable_qty_inc" padding="5" unsigned="true" nullable="false" identity="false" default="1"/>
    <column xsi:type="smallint" name="enable_qty_increments" padding="5" unsigned="true" nullable="false" identity="false" default="0"/>
    <column xsi:type="smallint" name="is_decimal_divided" padding="5" unsigned="true" nullable="false" identity="false" default="0"/>
    <column xsi:type="smallint" name="website_id" padding="5" unsigned="true" nullable="false" identity="false" default="0"/>
    <constraint xsi:type="primary" name="PRIMARY">
      <column name="item_id"/>
    </constraint>
    <constraint xsi:type="foreign" name="CATINV_STOCK_ITEM_PRD_ID_CAT_PRD_ENTT_ENTT_ID" table="cataloginventory_stock_item" column="product_id" referenceTable="catalog_product_entity" referenceColumn="entity_id" onDelete="CASCADE"/>
    <constraint xsi:type="foreign" name="CATINV_STOCK_ITEM_STOCK_ID_CATINV_STOCK_STOCK_ID" table="cataloginventory_stock_item" column="stock_id" referenceTable="cataloginventory_stock" referenceColumn="stock_id" onDelete="CASCADE"/>
    <constraint xsi:type="unique" name="CATALOGINVENTORY_STOCK_ITEM_PRODUCT_ID_STOCK_ID">
      <column name="product_id"/>
      <column name="stock_id"/>
    </constraint>
    <index name="CATALOGINVENTORY_STOCK_ITEM_WEBSITE_ID" indexType="btree">
      <column name="website_id"/>
    </index>
    <index name="CATALOGINVENTORY_STOCK_ITEM_STOCK_ID" indexType="btree">
      <column name="stock_id"/>
    </index>
  </table>
  <table name="cataloginventory_stock_status" resource="default" engine="innodb">
    <column xsi:type="int" name="product_id" padding="10" unsigned="true" nullable="false" identity="false"/>
    <column xsi:type="smallint" name="website_id" padding="5" unsigned="true" nullable="false" identity="false"/>
    <column xsi:type="smallint" name="stock_id" padding="5" unsigned="true" nullable="false" identity="false"/>
    <column xsi:type="decimal" name="qty" scale="4" precission="12" unsigned="false" nullable="false" default="0"/>
    <column xsi:type="smallint" name="stock_status" padding="5" unsigned="true" nullable="false" identity="false"/>
    <constraint xsi:type="primary" name="PRIMARY">
      <column name="product_id"/>
      <column name="website_id"/>
      <column name="stock_id"/>
    </constraint>
    <index name="CATALOGINVENTORY_STOCK_STATUS_STOCK_ID" indexType="btree">
      <column name="stock_id"/>
    </index>
    <index name="CATALOGINVENTORY_STOCK_STATUS_WEBSITE_ID" indexType="btree">
      <column name="website_id"/>
    </index>
    <index name="CATALOGINVENTORY_STOCK_STATUS_STOCK_STATUS" indexType="btree">
      <column name="stock_status"/>
    </index>
  </table>
  <table name="cataloginventory_stock_status_idx" resource="default" engine="innodb">
    <column xsi:type="int" name="product_id" padding="10" unsigned="true" nullable="false" identity="false"/>
    <column xsi:type="smallint" name="website_id" padding="5" unsigned="true" nullable="false" identity="false"/>
    <column xsi:type="smallint" name="stock_id" padding="5" unsigned="true" nullable="false" identity="false"/>
    <column xsi:type="decimal" name="qty" scale="4" precission="12" unsigned="false" nullable="false" default="0"/>
    <column xsi:type="smallint" name="stock_status" padding="5" unsigned="true" nullable="false" identity="false"/>
    <constraint xsi:type="primary" name="PRIMARY">
      <column name="product_id"/>
      <column name="website_id"/>
      <column name="stock_id"/>
    </constraint>
    <index name="CATALOGINVENTORY_STOCK_STATUS_IDX_STOCK_ID" indexType="btree">
      <column name="stock_id"/>
    </index>
    <index name="CATALOGINVENTORY_STOCK_STATUS_IDX_WEBSITE_ID" indexType="btree">
      <column name="website_id"/>
    </index>
  </table>
  <table name="cataloginventory_stock_status_tmp" resource="default" engine="memory">
    <column xsi:type="int" name="product_id" padding="10" unsigned="true" nullable="false" identity="false"/>
    <column xsi:type="smallint" name="website_id" padding="5" unsigned="true" nullable="false" identity="false"/>
    <column xsi:type="smallint" name="stock_id" padding="5" unsigned="true" nullable="false" identity="false"/>
    <column xsi:type="decimal" name="qty" scale="4" precission="12" unsigned="false" nullable="false" default="0"/>
    <column xsi:type="smallint" name="stock_status" padding="5" unsigned="true" nullable="false" identity="false"/>
    <constraint xsi:type="primary" name="PRIMARY">
      <column name="product_id"/>
      <column name="website_id"/>
      <column name="stock_id"/>
    </constraint>
    <index name="CATALOGINVENTORY_STOCK_STATUS_TMP_STOCK_ID" indexType="hash">
      <column name="stock_id"/>
    </index>
    <index name="CATALOGINVENTORY_STOCK_STATUS_TMP_WEBSITE_ID" indexType="hash">
      <column name="website_id"/>
    </index>
  </table>
  <table name="cataloginventory_stock_status_replica" resource="default" engine="innodb">
    <column xsi:type="int" name="product_id" padding="10" unsigned="true" nullable="false" identity="false"/>
    <column xsi:type="smallint" name="website_id" padding="5" unsigned="true" nullable="false" identity="false"/>
    <column xsi:type="smallint" name="stock_id" padding="5" unsigned="true" nullable="false" identity="false"/>
    <column xsi:type="decimal" name="qty" scale="4" precission="12" unsigned="false" nullable="false" default="0"/>
    <column xsi:type="smallint" name="stock_status" padding="5" unsigned="true" nullable="false" identity="false"/>
    <constraint xsi:type="primary" name="PRIMARY">
      <column name="product_id"/>
      <column name="website_id"/>
      <column name="stock_id"/>
    </constraint>
    <index name="CATALOGINVENTORY_STOCK_STATUS_REPLICA_STOCK_ID" indexType="btree">
      <column name="stock_id"/>
    </index>
    <index name="CATALOGINVENTORY_STOCK_STATUS_REPLICA_WEBSITE_ID" indexType="btree">
      <column name="website_id"/>
    </index>
    <index name="CATALOGINVENTORY_STOCK_STATUS_REPLICA_STOCK_STATUS" indexType="btree">
      <column name="stock_status"/>
    </index>
  </table>
</schema>
