=== tvorexspecialist/m2automation/app/code/Magento/GraphQl/etc/graphql.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="config" type="configType">
        <xs:annotation>
            <xs:documentation>Copyright Â© Magento, Inc. All rights reserved.
                See COPYING.txt for license details.
            </xs:documentation>
        </xs:annotation>
    </xs:element>

    <xs:complexType name="itemType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="configType" mixed="true">
        <xs:sequence>
            <xs:element type="abstractType" name="type" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="implementsType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="interface" use="required"/>
                <xs:attribute type="xs:string" name="copyFields" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="abstractType" abstract="true">
        <xs:attribute type="xs:string" name="description" use="optional"/>
    </xs:complexType>

    <xs:complexType name="Enum">
        <xs:complexContent>
            <xs:extension base="abstractType">
                <xs:sequence>
                    <xs:element type="EnumItem" name="item" maxOccurs="unbounded" minOccurs="0"/>
                </xs:sequence>
                <xs:attribute type="xs:string" name="name" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="EnumItem">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="name" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="InputType">
        <xs:complexContent>
            <xs:extension base="abstractType">
                <xs:choice maxOccurs="unbounded" minOccurs="0">
                    <xs:element type="AbstractField" name="field"/>
                </xs:choice>
                <xs:attribute name="name" type="InputTypeNameType" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="InputTypeNameType">
        <xs:restriction base="xs:string">
            <xs:pattern value=".*Input"><xs:annotation><xs:documentation>All input types must have "Input" suffix</xs:documentation></xs:annotation></xs:pattern>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="OutputType">
        <xs:complexContent>
            <xs:extension base="abstractType">
                <xs:choice maxOccurs="unbounded" minOccurs="0">
                    <xs:element type="AbstractField" name="field"/>
                    <xs:element type="implementsType" name="implements"/>
                </xs:choice>
                <xs:attribute type="xs:string" name="name" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="OutputInterface">
        <xs:complexContent>
            <xs:extension base="abstractType">
                <xs:choice maxOccurs="unbounded" minOccurs="0">
                    <xs:element type="AbstractField" name="field"/>
                </xs:choice>
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:string" name="typeResolver" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="AbstractField" abstract="true">
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute name="resolver" type="xs:string" use="optional"/>
        <xs:attribute name="required" type="xs:boolean" use="optional" default="false"/>
        <xs:attribute type="xs:string" name="description" use="optional"/>
    </xs:complexType>

    <xs:complexType name="AbstractInputField" abstract="true">
        <xs:complexContent>
            <xs:extension base="AbstractField" />
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="AbstractOutputField" abstract="true">
        <xs:complexContent>
            <xs:extension base="AbstractField">
                <xs:sequence>
                    <xs:element type="AbstractArgument" name="argument" maxOccurs="unbounded" minOccurs="0"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ScalarOutputField">
        <xs:complexContent>
            <xs:extension base="AbstractOutputField">
                <xs:attribute type="GraphQlScalarTypesEnum" name="type" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ScalarInputField">
        <xs:complexContent>
            <xs:extension base="AbstractInputField">
                <xs:attribute type="GraphQlScalarTypesEnum" name="type" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ObjectOutputField">
        <xs:complexContent>
            <xs:extension base="AbstractOutputField">
                <xs:attribute type="xs:string" name="type" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ObjectInputField">
        <xs:complexContent>
            <xs:extension base="AbstractInputField">
                <xs:attribute type="xs:string" name="type" use="optional"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ScalarArrayOutputField">
        <xs:complexContent>
            <xs:extension base="AbstractOutputField">
                <xs:attribute name="itemType" type="GraphQlScalarTypesEnum" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ScalarArrayInputField">
        <xs:complexContent>
            <xs:extension base="AbstractInputField">
                <xs:attribute name="itemType" type="GraphQlScalarTypesEnum" use="required"/>
                <xs:attribute name="itemsRequired" type="xs:boolean" use="optional" default="false"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ObjectArrayOutputField">
        <xs:complexContent>
            <xs:extension base="AbstractOutputField">
                <xs:attribute name="itemType" type="xs:string" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ObjectArrayInputField">
        <xs:complexContent>
            <xs:extension base="AbstractInputField">
                <xs:attribute name="itemType" type="xs:string" use="required"/>
                <xs:attribute name="itemsRequired" type="xs:boolean" use="optional" default="false"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="AbstractArgument" abstract="true">
        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute name="required" type="xs:boolean" use="optional" default="false"/>
        <xs:attribute type="xs:string" name="description" use="optional"/>
    </xs:complexType>

    <xs:complexType name="ScalarArgument">
        <xs:complexContent>
            <xs:extension base="AbstractArgument">
                <xs:attribute type="GraphQlScalarTypesEnum" name="type" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ObjectArgument">
        <xs:complexContent>
            <xs:extension base="AbstractArgument">
                <xs:attribute type="xs:string" name="type" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ScalarArrayArgument">
        <xs:complexContent>
            <xs:extension base="AbstractArgument">
                <xs:attribute name="itemType" type="GraphQlScalarTypesEnum" use="required"/>
                <xs:attribute name="itemsRequired" type="xs:boolean" use="optional" default="false"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ObjectArrayArgument">
        <xs:complexContent>
            <xs:extension base="AbstractArgument">
                <xs:attribute name="itemType" type="xs:string" use="required"/>
                <xs:attribute name="itemsRequired" type="xs:boolean" use="optional" default="false"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="SortArgument">
        <xs:complexContent>
            <xs:extension base="AbstractArgument">
                <xs:attribute name="baseType" type="xs:string" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="FilterArgument">
        <xs:complexContent>
            <xs:extension base="AbstractArgument">
                <xs:attribute type="xs:string" name="baseType" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="arrayItemType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="type"/>
                <xs:attribute type="xs:string" name="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="GraphQlScalarTypesEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Int"/>
            <xs:enumeration value="String"/>
            <xs:enumeration value="Boolean"/>
            <xs:enumeration value="Float"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== tvorexspecialist/m2automation/app/code/Magento/CatalogUrlRewriteGraphQl/etc/graphql.xml
<?xml version="1.0"?>
<!--
  Copyright Â© Magento, Inc. All rights reserved.
  See COPYING.txt for license details.
  -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_GraphQl:etc/graphql.xsd">
    <type xsi:type="OutputInterface" name="ProductInterface">
        <field xsi:type="ScalarOutputField" name="url_key" type="String"/>
        <field xsi:type="ScalarOutputField" name="url_path" type="String"/>
    </type>
    <type xsi:type="InputType" name="ProductFilterInput">
        <field xsi:type="ObjectInputField" name="url_key" type="FilterTypeInput"/>
        <field xsi:type="ObjectInputField" name="url_path" type="FilterTypeInput"/>
    </type>
    <type xsi:type="InputType" name="ProductSortInput">
        <field xsi:type="ObjectInputField" name="url_key" type="SortEnum"/>
        <field xsi:type="ObjectInputField" name="url_path" type="SortEnum"/>
    </type>
    <type xsi:type="Enum" name="UrlRewriteEntityTypeEnum">
        <item name="PRODUCT">PRODUCT</item>
        <item name="CATEGORY">CATEGORY</item>
    </type>
</config>

=== tvorexspecialist/m2automation/app/code/Magento/UrlRewriteGraphQl/etc/graphql.xml
<?xml version="1.0"?>
<!--
  Copyright Â© Magento, Inc. All rights reserved.
  See COPYING.txt for license details.
  -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_GraphQl:etc/graphql.xsd">
    <type xsi:type="OutputType" name="Query">
        <field xsi:type="ObjectOutputField" name="urlResolver" type="EntityUrl" resolver="Magento\UrlRewriteGraphQl\Model\Resolver\UrlRewrite">
            <argument xsi:type="ScalarArgument" name="url" type="String" required="true"/>
         </field>
    </type>
    <type xsi:type="OutputType" name="EntityUrl">
        <field xsi:type="ScalarOutputField" name="id" type="Int"/>
        <field xsi:type="ScalarOutputField" name="canonical_url" type="String"/>
        <field xsi:type="ObjectOutputField" name="type" type="UrlRewriteEntityTypeEnum"/>
    </type>
    <type xsi:type="Enum" name="UrlRewriteEntityTypeEnum"/>
</config>

=== tvorexspecialist/m2automation/app/code/Magento/DownloadableGraphQl/etc/graphql.xml
<?xml version="1.0"?>
<!--
  Copyright Â© Magento, Inc. All rights reserved.
  See COPYING.txt for license details.
  -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_GraphQl:etc/graphql.xsd">
    <type xsi:type="OutputType" name="DownloadableProduct">
        <implements interface="ProductInterface" copyFields="true"/>
        <field xsi:type="ObjectArrayOutputField" name="downloadable_product_samples" itemType="DownloadableProductSamples"/>
        <field xsi:type="ObjectArrayOutputField" name="downloadable_product_links" itemType="DownloadableProductLinks"/>
        <field xsi:type="ObjectOutputField" name="links_purchased_separately" type="Int"/>
        <field xsi:type="ObjectOutputField" name="links_title" type="String"/>
        <!-- INVESTIGATE CUSTOM ATTRIBUTES WHY ARE NOT BEING ADDED AUTOMATICALLY -->
        <field xsi:type="ObjectOutputField" name="color" type="Int"/>
        <field xsi:type="ObjectOutputField" name="size" type="String"/>
        <field xsi:type="ObjectOutputField" name="manufacturer" type="Int"/>
    </type>
    <type xsi:type="OutputType" name="DownloadableProductSamples">
        <field xsi:type="ObjectOutputField" name="id" type="Int"/>
        <field xsi:type="ObjectOutputField" name="title" type="String"/>
        <field xsi:type="ObjectOutputField" name="sort_order" type="Int"/>
        <field xsi:type="ObjectOutputField" name="sample_type" type="DownloadableFileTypeEnum"/>
        <field xsi:type="ObjectOutputField" name="sample_file" type="String"/>
        <field xsi:type="ObjectOutputField" name="sample_url" type="String"/>
    </type>
    <type xsi:type="OutputType" name="DownloadableProductLinks">
        <field xsi:type="ObjectOutputField" name="id" type="Int"/>
        <field xsi:type="ObjectOutputField" name="title" type="String"/>
        <field xsi:type="ObjectOutputField" name="sort_order" type="Int"/>
        <field xsi:type="ObjectOutputField" name="is_shareable" type="Boolean"/>
        <field xsi:type="ObjectOutputField" name="price" type="Float"/>
        <field xsi:type="ObjectOutputField" name="number_of_downloads" type="Int"/>
        <field xsi:type="ObjectOutputField" name="link_type" type="DownloadableFileTypeEnum"/>
        <field xsi:type="ObjectOutputField" name="sample_type" type="DownloadableFileTypeEnum"/>
        <field xsi:type="ObjectOutputField" name="sample_file" type="String"/>
        <field xsi:type="ObjectOutputField" name="sample_url" type="String"/>
    </type>
    <type xsi:type="Enum" name="DownloadableFileTypeEnum">
        <item name="file">FILE</item>
        <item name="url">URL</item>
    </type>
</config>

=== tvorexspecialist/m2automation/app/code/Magento/CustomerGraphQl/etc/graphql.xml
<?xml version="1.0"?>
<!--
  Copyright Â© Magento, Inc. All rights reserved.
  See COPYING.txt for license details.
  -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_GraphQl:etc/graphql.xsd">
    <type xsi:type="OutputType" name="Query">
        <field xsi:type="ObjectOutputField" name="customer" type="Customer" resolver="Magento\CustomerGraphQl\Model\Resolver\Customer"/>
    </type>
    <type xsi:type="OutputType" name="Customer">
        <field xsi:type="ScalarOutputField" name="created_at" type="String"/>
        <field xsi:type="ScalarOutputField" name="group_id" type="Int"/>
        <field xsi:type="ScalarOutputField" name="prefix" type="String"/>
        <field xsi:type="ScalarOutputField" name="firstname" type="String"/>
        <field xsi:type="ScalarOutputField" name="middlename" type="String"/>
        <field xsi:type="ScalarOutputField" name="lastname" type="String"/>
        <field xsi:type="ScalarOutputField" name="suffix" type="String"/>
        <field xsi:type="ScalarOutputField" name="email" type="String"/>
        <field xsi:type="ScalarOutputField" name="default_billing" type="String"/>
        <field xsi:type="ScalarOutputField" name="default_shipping" type="String"/>
        <field xsi:type="ScalarOutputField" name="dob" type="String"/>
        <field xsi:type="ScalarOutputField" name="taxvat" type="String"/>
        <field xsi:type="ScalarOutputField" name="id" type="Int"/>
        <field xsi:type="ScalarOutputField" name="dob" type="String"/>
        <field xsi:type="ScalarOutputField" name="is_subscribed" type="Boolean"/>
        <field xsi:type="ObjectArrayOutputField" name="addresses" itemType="CustomerAddress"/>
    </type>
    <type xsi:type="OutputType" name="CustomerAddress">
        <field xsi:type="ScalarOutputField" name="id" type="Int"/>
        <field xsi:type="ScalarOutputField" name="customer_id" type="Int"/>
        <field xsi:type="ObjectOutputField" name="region" type="CustomerAddressRegion"/>
        <field xsi:type="ScalarOutputField" name="region_id" type="Int"/>
        <field xsi:type="ScalarOutputField" name="country_id" type="String"/>
        <field xsi:type="ScalarArrayOutputField" name="street" itemType="String"/>
        <field xsi:type="ScalarOutputField" name="company" type="String"/>
        <field xsi:type="ScalarOutputField" name="telephone" type="String"/>
        <field xsi:type="ScalarOutputField" name="fax" type="String"/>
        <field xsi:type="ScalarOutputField" name="postcode" type="String"/>
        <field xsi:type="ScalarOutputField" name="city" type="String"/>
        <field xsi:type="ScalarOutputField" name="firstname" type="String"/>
        <field xsi:type="ScalarOutputField" name="lastname" type="String"/>
        <field xsi:type="ScalarOutputField" name="middlename" type="String"/>
        <field xsi:type="ScalarOutputField" name="prefix" type="String"/>
        <field xsi:type="ScalarOutputField" name="suffix" type="String"/>
        <field xsi:type="ScalarOutputField" name="vat_id" type="String"/>
        <field xsi:type="ScalarOutputField" name="default_shipping" type="Boolean"/>
        <field xsi:type="ScalarOutputField" name="default_billing" type="Boolean"/>
    </type>
    <type xsi:type="OutputType" name="CustomerAddressRegion">
        <field xsi:type="ScalarOutputField" name="region_code" type="String"/>
        <field xsi:type="ScalarOutputField" name="region" type="String"/>
        <field xsi:type="ScalarOutputField" name="region_id" type="Int"/>
    </type>
</config>

=== tvorexspecialist/m2automation/app/code/Magento/TaxGraphQl/etc/graphql.xml
<?xml version="1.0"?>
<!--
  Copyright Â© Magento, Inc. All rights reserved.
  See COPYING.txt for license details.
  -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_GraphQl:etc/graphql.xsd">
    <type xsi:type="OutputInterface" name="ProductInterface">
        <field xsi:type="ScalarOutputField" name="tax_class_id" type="Int" description="An ID assigned to a tax class. "/>
    </type>
    <type xsi:type="InputType" name="ProductFilterInput">
        <field xsi:type="ObjectInputField" name="tax_class_id" type="FilterTypeInput" description="An ID assigned to a tax class."/>
    </type>
    <type xsi:type="InputType" name="ProductSortInput">
        <field xsi:type="ObjectInputField" name="tax_class_id" type="SortEnum" description="An ID assigned to a tax class."/>
    </type>
    <type xsi:type="Enum" name="PriceAdjustmentCodesEnum">
        <item name="tax">TAX</item>
    </type>
</config>

=== tvorexspecialist/m2automation/dev/tests/integration/testsuite/Magento/Framework/GraphQl/_files/graphql_config2.xml
<?xml version="1.0"?>
<!--
  Copyright Â© Magento, Inc. All rights reserved.
  See COPYING.txt for license details.
  -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_GraphQl:etc/graphql.xsd">
    <type xsi:type="OutputType" name="Query">
        <field xsi:type="ScalarOutputField" name="mergedField" type="Int" description="test field description" resolver="testResolverPath">
            <argument xsi:type="ScalarArgument" name="mergedArgument" type="String" description="test argument description"/>
        </field>
    </type>
    <type xsi:type="Enum" name="PriceAdjustmentDescriptionEnum">
        <item name="included">INCLUDED</item>
        <item name="excluded">EXCLUDED</item>
        <item name="mergedItem">MERGEDITEM</item>
    </type>
    <type xsi:type="OutputType" name="ProductLinks">
        <implements interface="MergedInterface" copyFields="true"/>
    </type>
    <type xsi:type="OutputInterface" name="MergedInterface" typeResolver="resolverPath">
        <field xsi:type="ScalarOutputField" name="mergedFieldN" type="String" description="The identifier of the linked merged product"/>
    </type>
</config>
